# Postgres

default: &default
  adapter: postgresql 
  encoding: utf8 
  database: docker 
  username: docker 
  password: docker
  pool: 5 # not mandatory     
  timeout: 5000 # not mandatory 
  host: 188.166.29.77 
  port: 32769

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default